### ISSUE TITLE
How to run tests on bitbucket pull request 

### ISSUE THREAD

**Issue by tawanda** [Karunamon/concourse-resource-bitbucket#1]
Thanks a lot for building this

May you help me with this

Everytime a developer submits a pull request i would like it to trigger a build with that pull requests code and run tests, then if the tests pass i can do a code review

Is this possible with your plugin or would it need to be modified

**Comment by Karunamon** [comment]
Hi there, apologies for the long delay in getting back to you.

As it stands, that would need to be a check/in resource, which *right now*, hasn't been written yet.

The plugin is strictly output only, but it should be simple enough to add on that functionality. This may take me some time though, since initially writing this, I've had very little time to mess with Concourse. It is on my radar, however.

**Comment by tawanda** [comment]
Thanks for this. Will keep an eye out

**Comment by aecepoglu** [comment]
Guys, I have implemented a concourse resource that deals with this. I'll push it to a github repository and put a link to it as well as an example of how to do pr-builds.

**Comment by tawanda** [comment]
please post the link in this chat that would be really helpful

**Comment by moskalyk** [comment]
@aecepoglu is there any update on a Bitbucket PR resource? Funny enough, my team and I are just encountering this problem as well. It's do or die for Concourse right now if we cant get this to work for our CD pipeline!

**Comment by aecepoglu** [comment]
I was thinking of working a little bit longer on it before I released,
but OK I'm gonna put it up right now

**Comment by aecepoglu** [comment]
@tawanda @moskalyk Here it is. I was going to refine it a little bit before I put it online but I suppose you guys needed it urgently so I rushed it a little bit. The documentation may not be enough so feel free to ask me for clarifications (in the other repo so we don't disturb this one so much)

**Comment by tawanda** [comment]
Many thanks
