### ISSUE TITLE
Bitbucket returning 404

### ISSUE THREAD

**Issue by leeola** [Karunamon/concourse-resource-bitbucket#10]
Any have any idea why this resource would get a 404 from bitbucket? Did the API change and this resource isn't updated?

**Comment by elementsweb** [comment]
This resource currently only supports Bitbucket Server (the version you download, install and host yourself). You would then have to provide the resource the URL to **your** instance of Bitbucket Server.

If you are looking for Bitbucket Cloud support (the version you simply login to online and is hosted by Atlassian), take a look at this [pull request](https://github.com/Karunamon/concourse-resource-bitbucket/pull/8) which adds the Bitbucket Cloud support. You may have to clone the repository, build and host your own Docker image. I've managed to get this working with Bitbucket Cloud successfully.

**Comment by leeola** [comment]
Appreciate the info, thank you very much!
