### ISSUE TITLE
Could not read Username

### ISSUE THREAD

**Issue by dignajar** [Karunamon/concourse-resource-bitbucket#9]
Hi, I have a little issue when try to connect to the bitbucket:

this is my pipeline:
```
---
resource_types:
- name: bitbucket-notify
  type: docker-image
  source:
    repository: karunamon/concourse-resource-bitbucket

resources:
- name: concourse-test
  type: git
  source:
    uri: https://bitbucket.org/{USERNAME}/concourse-test.git
    branch: master

- name: bitbucket-notify
  type: bitbucket-notify
  source:
    bitbucket_url: https://bitbucket.org/{USERNAME}/
    bitbucket_username: {USERNAME}
    bitbucket_password: {PASSWORD}
    debug: true
    verify_ssl: true

jobs:
- name: job_helloworld
  plan:
  - get: concourse-test
    trigger: true

  - put: bitbucket-notify
    params:
      build_status: INPROGRESS
      repo: concourse-test

  - task: task_helloworld
    file: concourse-test/tasks/helloworld/task.yml
```

The error on concourse-test

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: could not read Username for 'https://bitbucket.org': No such device or address
```

**Comment by elementsweb** [comment]
Firstly you need to make sure you are using variables correctly in your pipeline configuration file. Variables should be enclosed with double curly braces (e.g. `{{USERNAME}}`).

Secondly make sure you are passing in the variable when setting the pipeline:
```
fly -t lite set-pipeline -p my-pipeline -c pipeline.yml --var "USERNAME=elementsweb" --var "PASSWORD=password123"
```

Thirdly this resource works for Bitbucket Server at the moment (previously called Stash) and is different to Bitbucket Cloud in that you install Bitbucket Server on your own server/s. Therefore your Bitbucket URL you used: `https://bitbucket.org/{USERNAME}/` is highly likely to be wrong.

If you want a solution that works for your Bitbucket Server installation, use the URL you've configured it to use (most likely a domain name you own or just an IP address). If you want a solution for Bitbucket Cloud take a look at the [pull request](https://github.com/Karunamon/concourse-resource-bitbucket/pull/8) for adding this support - you may need to clone down their repository, build and host the docker image yourself. If you're unsure how to do this just shout. I've also written my own version that works with Bitbucket Cloud using the latest version 2 API if you would like me to publicise the repo and associated Docker image.
